kind: pipeline
type: docker
name: default

steps:

- name: restore-cache
  image: meltwater/drone-cache:1
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: cache_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: cache_secret
  pull: true
  settings:
    endpoint:
      from_secret: cache_endpoint
    restore: true
    bucket: new-eden-social-build-cache
    region: fra1
    path_style: true
    debug: true
    mount:
      - 'bazel_cache'
      - 'node_modules'
  when:
    event: [ push ]

- name: build-test
  image: node:lts
  commands:
  - yarn
  - yarn lint
  - yarn bazel:lint
  - yarn build --disk_cache=bazel_cache
  #- yarn test

- name: store-cache
  image: meltwater/drone-cache:1
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: cache_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: cache_secret
  pull: true
  settings:
    endpoint:
      from_secret: cache_endpoint
    rebuild: true
    bucket: new-eden-social-build-cache
    region: fra1
    debug: true
    path_style: true
    mount:
      - 'bazel_cache'
      - 'node_modules'
  when:
    event: [ push ]
