kind: pipeline
type: docker
name: default
steps:

# On TAG we push to production
- name: build-test
  image: node:lts
  environment:
    CACHE_GOOGLE_CREDENTIALS_FILE:
      from_secret: cache_google_credentials_file
    REGISTRY_GOOGLE_CREDENTIALS_FILE:
      from_secret: registry_production_google_credentials_file
    GOOGLE_APPLICATION_CREDENTIALS: .creds-registry.json
    SKAFFOLD_DEFAULT_REPO: eu.gcr.io/new-eden-social-production
  commands:
  - export PATH=$PATH:/tmp/google-cloud-sdk/bin
  - ./tools/prepare-ci.sh
  - yarn
  - yarn lint
  - yarn build:skaffold
  #- yarn test
  when:
    event:
    - tag

# Every other time we push to development
- name: build-test
  image: node:lts
  environment:
    CACHE_GOOGLE_CREDENTIALS_FILE:
      from_secret: cache_google_credentials_file
    REGISTRY_GOOGLE_CREDENTIALS_FILE:
      from_secret: registry_develop_google_credentials_file
    GOOGLE_APPLICATION_CREDENTIALS: .creds-registry.json
    SKAFFOLD_DEFAULT_REPO: eu.gcr.io/new-eden-social-production
  commands:
  - export PATH=$PATH:/tmp/google-cloud-sdk/bin
  - ./tools/prepare-ci.sh
  - yarn
  - yarn lint
  - yarn build:skaffold
  #- yarn test
  when:
    exclude:
    - tag
