kind: pipeline
type: docker
name: default

steps:

- name: restore-cache
  image: meltwater/drone-cache:1
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: cache_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: cache_secret
  pull: true
  settings:
    endpoint:
      from_secret: cache_endpoint
    restore: true
    bucket: new-eden-social-build-cache
    region: us-east-1
    debug: true
    mount:
      - node_modules
  when:
    event: [ push ]

- name: build-test
  image: node:lts
  environment:
    CACHE_GOOGLE_CREDENTIALS_FILE:
      from_secret: cache_google_credentials_file
  commands:
  - echo $CACHE_GOOGLE_CREDENTIALS_FILE > creds.json
  - yarn
  - yarn lint
  - yarn build --google_credentials=creds.json --remote_upload_local_results=true
  #- yarn test

- name: store-cache
  image: meltwater/drone-cache:1
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: cache_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: cache_secret
  pull: true
  settings:
    endpoint:
      from_secret: cache_endpoint
    rebuild: true
    bucket: new-eden-social-build-cache
    region: us-east-1
    debug: true
    path_style: true
    mount:
      - node_modules
  when:
    event: [ push ]
