kind: pipeline
type: docker
name: default

steps:

- name: restore
  image: plugins/s3-cache
  settings:
    pull: true
    endpoint:
      from_secret: cache_endpoint
    access_key:
      from_secret: cache_key
    secret_key:
      from_secret: cache_secret
    restore: true

- name: build-test
  image: node:lts
  commands:
  - yarn
  - yarn lint
  - yarn bazel:lint
  - yarn build --disk_cache=bazel_cache
  - yarn test

- name: rebuild
  image: plugins/s3-cache
  settings:
    pull: true
    endpoint:
      from_secret: cache_endpoint
    access_key:
      from_secret: cache_key
    secret_key:
      from_secret: cache_secret
    rebuild: true
    mount:
      - node_modules
      - bazel_cache
    when:
      event: push
