kind: pipeline
type: docker
name: default

steps:

steps:
- name: restore-cache
  image: meltwater/drone-cache
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: cache_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: cache_secret
  pull: true
  settings:
    endpoint:
      from_secret: cache_endpoint
    restore: true
    cache_key: {{ .Commit.Branch }} #-{{ checksum "go.mod" }} # default if ommitted is {{ .Commit.Branch }}
    bucket: new-eden-social-build-cache
    region: ""
    mount:
      - 'bazel_cache'
      - 'node_modules'

- name: build-test
  image: node:lts
  commands:
  - yarn
  - yarn lint
  - yarn bazel:lint
  - yarn build --disk_cache=bazel_cache
  - yarn test

- name: store-cache
  image: meltwater/drone-cache
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: cache_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: cache_secret
  pull: true
  settings:
    endpoint:
      from_secret: cache_endpoint
    rebuild: true
    cache_key: {{ .Commit.Branch }} #-{{ checksum "go.mod" }} # default if ommitted is {{ .Commit.Branch }}
    bucket: new-eden-social-build-cache
    region: ""
    mount:
      - 'bazel_cache'
      - 'node_modules'
