apiVersion: skaffold/v1beta13
kind: Config

build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: eu.gcr.io/new-eden-social-development/services-alliance
    bazel:
      target: //src/services/alliance:docker.tar
  - image: eu.gcr.io/new-eden-social-development/services-authenticate
    bazel:
      target: //src/services/authenticate:docker.tar
  - image: eu.gcr.io/new-eden-social-development/services-character
    bazel:
      target: //src/services/character:docker.tar
  - image: eu.gcr.io/new-eden-social-development/services-comment
    bazel:
      target: //src/services/comment:docker.tar
  - image: eu.gcr.io/new-eden-social-development/services-corporation
    bazel:
      target: //src/services/corporation:docker.tar
  - image: eu.gcr.io/new-eden-social-development/services-follow
    bazel:
      target: //src/services/follow:docker.tar
  - image: eu.gcr.io/new-eden-social-development/services-hashtag
    bazel:
      target: //src/services/hashtag:docker.tar
  - image: eu.gcr.io/new-eden-social-development/services-killmail
    bazel:
      target: //src/services/killmail:docker.tar
  - image: eu.gcr.io/new-eden-social-development/services-metascraper
    bazel:
      target: //src/services/metascraper:docker.tar
  - image: eu.gcr.io/new-eden-social-development/services-notification
    bazel:
      target: //src/services/notification:docker.tar
  - image: eu.gcr.io/new-eden-social-development/services-post
    bazel:
      target: //src/services/post:docker.tar
  - image: eu.gcr.io/new-eden-social-development/services-search
    bazel:
      target: //src/services/search:docker.tar
  - image: eu.gcr.io/new-eden-social-development/services-universe
    bazel:
      target: //src/services/universe:docker.tar
  - image: eu.gcr.io/new-eden-social-development/services-updater
    bazel:
      target: //src/services/updater:docker.tar
  - image: eu.gcr.io/new-eden-social-development/services-websocket
    bazel:
      target: //src/services/websocket:docker.tar
