apiVersion: skaffold/v1beta13
kind: Config

build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: services-alliance
    bazel:
      target: //src/services/alliance:docker.tar
  - image: services-authenticate
    bazel:
      target: //src/services/authenticate:docker.tar
  - image: services-character
    bazel:
      target: //src/services/character:docker.tar
  - image: services-comment
    bazel:
      target: //src/services/comment:docker.tar
  - image: services-corporation
    bazel:
      target: //src/services/corporation:docker.tar
  - image: services-follow
    bazel:
      target: //src/services/follow:docker.tar
  - image: services-hashtag
    bazel:
      target: //src/services/hashtag:docker.tar
  - image: services-killmail
    bazel:
      target: //src/services/killmail:docker.tar
  - image: services-metascraper
    bazel:
      target: //src/services/metascraper:docker.tar
  - image: services-notification
    bazel:
      target: //src/services/notification:docker.tar
  - image: services-post
    bazel:
      target: //src/services/post:docker.tar
  - image: services-search
    bazel:
      target: //src/services/search:docker.tar
  - image: services-universe
    bazel:
      target: //src/services/universe:docker.tar
  - image: services-updater
    bazel:
      target: //src/services/updater:docker.tar
  - image: services-websocket
    bazel:
      target: //src/services/websocket:docker.tar


deploy:
  helm:
    releases:
    - name: alliances
      chartPath: charts/alliances
