version: 2.1

commands:
  authenticate_docker_hub:
    description: "Authenticate with Docker Hub"
    steps:
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  pull_tag_push:
    description: "Pull, Tag and Push image"
    parameters:
      image:
        type: string
      tag:
        type: string
    steps:
      - run: docker pull << parameters.image >>:$CIRCLE_SHA1
      - run: docker tag << parameters.image >>:<< parameters.tag >>
      - run: docker push << parameters.image >>:<< parameters.tag >>
  demo_deploy:
    description: "Placeholder for real deploy logic"
    steps:
      - run: echo "Hello world, this should be deployed!"

executors:
  node-test:
    docker:
      - image: circleci/node:lts
  docker-build:
    machine:
      image: circleci/classic:201808-01

jobs:
  build-api:
    executor: docker-build
    steps:
     - checkout
     - authenticate_docker_hub
     - run:
        name: Building image
        working_directory: api
        command: docker build . -t newedensocial/api:$CIRCLE_SHA1
     - run:
        name: Push Image
        command: docker push newedensocial/api:$CIRCLE_SHA1

  build-web:
    executor: docker-build
    steps:
     - checkout
     - authenticate_docker_hub
     - run:
        name: Building image
        working_directory: web
        command: docker build . -t newedensocial/web:$CIRCLE_SHA1
     - run:
        name: Push Image
        command: docker push newedensocial/web:$CIRCLE_SHA1

  test-lint-api:
    executor: node-test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-api-node-modules-{{ .Branch }}-
            - v1-api-node-modules-master-
      - run:
          name: Install Dependencies
          working_directory: api
          command: yarn
      - save_cache:
          key: v1-api-node-modules-{{ .Branch }}-{{ epoch }}
          paths:
            - /app/api/node_modules
      - run:
          name: Run Linter
          working_directory: api
          command: yarn lint

  test-lint-web:
    executor: node-test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-web-node-modules-{{ .Branch }}-
            - v1-web-node-modules-master-
      - run:
          name: Install Dependencies
          working_directory: web
          command: yarn
      - save_cache:
          key: v1-web-node-modules-{{ .Branch }}-{{ epoch }}
          paths:
            - /app/web/node_modules
      - run:
          name: Run Linter
          working_directory: web
          command: yarn lint

  test-api:
    executor: node-test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-api-node-modules-{{ .Branch }}-
            - v1-api-node-modules-master-
      - run:
          name: Install Dependencies
          working_directory: api
          command: yarn
      - save_cache:
          key: v1-api-node-modules-{{ .Branch }}-{{ epoch }}
          paths:
            - /app/api/node_modules
      - run:
          name: Run Tests
          working_directory: api
          command: yarn test

  test-web:
    executor: node-test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-web-node-modules-{{ .Branch }}-
            - v1-web-node-modules-master-
      - run:
          name: Install Dependencies
          working_directory: web
          command: yarn
      - save_cache:
          key: v1-web-node-modules-{{ .Branch }}-{{ epoch }}
          paths:
            - /app/web/node_modules
      - run:
          name: Run Tests
          working_directory: web
          command: yarn test

  push_latest:
    executor: docker-build
    steps:
      - authenticate_docker_hub
      - pull_tag_push:
          image: new-eden-social/api
          tag: latest
      - pull_tag_push:
          image: new-eden-social/web
          tag: latest

  push_release:
    executor: docker-build
    steps:
      - authenticate_docker_hub
      - pull_tag_push:
          image: new-eden-social/api
          tag: $CIRCLE_TAG
      - pull_tag_push:
          image: new-eden-social/web
          tag: $CIRCLE_TAG

  deploy_latest:
    executor: docker-build
    steps:
      - demo_deploy

  deploy_release:
    executor: docker-build
    steps:
      - demo_deploy

workflows:
  version: 2
  feature-branch-workflow:
    jobs:
      - test-lint-api
      - test-lint-web
      - test-api
      - test-web
      - build-api
      - build-web
      # Release latest version
      - push_latest:
          requires:
            - test-lint-api
            - test-lint-web
            - test-api
            - test-web
            - build-api
            - build-web
          filters:
            branches:
              only: master
      - deploy_latest:
          requires:
            - push_latest
          filters:
            branches:
              only: master
      # Release new version
      - push_release:
          requires:
            - test-lint-api
            - test-lint-web
            - test-api
            - test-web
            - build-api
            - build-web
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - deploy_release:
          requires:
            - push_release
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
