version: 2.1

commands:
  authenticate_docker_hub:
    description: "Authenticate with Docker Hub"
    steps:
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  pull_tag_push:
    description: "Pull, Tag and Push image"
    parameters:
      image:
        type: string
      tag:
        type: string
    steps:
      - run: docker pull << parameters.image >>:$CIRCLE_SHA1
      - run: docker tag << parameters.image >>:$CIRCLE_SHA1 << parameters.image >>:<< parameters.tag >>
      - run: docker push << parameters.image >>:<< parameters.tag >>
  pull_tag:
    description: "Pull and Tag image"
    parameters:
      image:
        type: string
      tag:
        type: string
    steps:
      - run: docker pull << parameters.image >>:$CIRCLE_SHA1
      - run: docker tag << parameters.image >>:$CIRCLE_SHA1 << parameters.image >>:<< parameters.tag >>
  demo_deploy:
    description: "Placeholder for real deploy logic"
    steps:
      - run: echo "Hello world, this should be deployed!"

executors:
  node-test:
    docker:
      - image: circleci/node:lts

jobs:
  build:
    executor: node-test
    steps:
      - checkout
      - authenticate_docker_hub
      - restore_cache:
          keys:
            - v2-node-modules-{{ .Branch }}-
            - v2-node-modules-master-
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive
      - save_cache:
          key: v2-node-modules-{{ .Branch }}-{{ epoch }}
          paths:
            - /app/node_modules
      - run:
          name: Run Build
          command: yarn build

  test-lint:
    executor: node-test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-modules-{{ .Branch }}-
            - v2-node-modules-master-
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive
      - save_cache:
          key: v2-node-modules-{{ .Branch }}-{{ epoch }}
          paths:
            - /app/node_modules
      - run:
          name: Run Linter
          command: yarn lint

  test:
    executor: node-test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-modules-{{ .Branch }}-
            - v2-node-modules-master-
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive
      - save_cache:
          key: v2-node-modules-{{ .Branch }}-{{ epoch }}
          paths:
            - /app/node_modules
      - run:
          name: Run Tests
          command: yarn test

  # TODO: Not bazel compatible
  push_latest:
    executor: node-test
    steps:
      - authenticate_docker_hub

  # TODO: Not bazel compatible
  push_release:
    executor: node-test
    steps:
      - authenticate_docker_hub

  deploy_latest:
    executor: node-test
    steps:
      - demo_deploy

  deploy_release:
    executor: node-test
    steps:
      - demo_deploy

workflows:
  version: 2
  feature-branch-workflow:
    jobs:
      - test-lint
      - test
      - build
      # Release latest version
      - push_latest:
          requires:
            - test-lint
            - test
            - build
          filters:
            branches:
              only: master
      - deploy_latest:
          requires:
            - push_latest
          filters:
            branches:
              only: master
      # Release new version
      - push_release:
          requires:
            - test-lint
            - test
            - build
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
      - deploy_release:
          requires:
            - push_release
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /^v.*/
